process.env.MONGO_USER="amanu"
process.env.MONGO_PASSWORD="ZCiqliv5OyJnXaWy"
process.env.MONGO_DEFAULT_DATABASE="shop"
process.env.STRIPE_KEY="sk_test_51LIbEuE5tiARmcipvFCR7aziAmg2gDDFu98bE3xLe0U6rq8Spr8pSXn94jl5azMpSqEGMN9hVEDXO00H6ulzxKpw00WOQTzVfP"
process.env.NODE_ENV="production"